# generated by datamodel-codegen:
#   filename:  answer_questions_model.json
#   timestamp: 2024-03-15T15:07:23+00:00

from __future__ import annotations
from malevich.square import scheme

from typing import Optional

from pydantic import BaseModel, Field


scheme()
class AnswerQuestions(BaseModel):
    model: Optional[str] = Field(
        'deepset/roberta-base-squad2',
        description='Name of the model to use in the pipeline',
    )
