# generated by datamodel-codegen:
#   filename:  classify_text_model.json
#   timestamp: 2024-03-05T17:40:30+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ClassifyText(BaseModel):
    model: str = Field(
        ..., description='default "distilbert-base-uncased-finetuned-sst-2-english"'
    )
    top_k: int = Field(..., description='default 1')
    functions_to_apply: str = Field(..., description='default "default"')
