# generated by datamodel-codegen:
#   filename:  classify_text_model.json
#   timestamp: 2024-03-06T12:29:20+00:00

from __future__ import annotations
from malevich.square import scheme

from pydantic import BaseModel, Field


scheme()
class ClassifyText(BaseModel):
    model: str = Field(
        ..., description='default "distilbert-base-uncased-finetuned-sst-2-english"'
    )
    top_k: int = Field(..., description='default 1')
    functions_to_apply: str = Field(..., description='default "default"')
