# generated by datamodel-codegen:
#   filename:  summarize_text_model.json
#   timestamp: 2024-03-05T17:40:30+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SummarizeText(BaseModel):
    model: str = Field(..., description="default 'none'")
