# generated by datamodel-codegen:
#   filename:  summarize_text_model.json
#   timestamp: 2024-03-13T13:02:50+00:00

from __future__ import annotations

from typing import Optional

from malevich.square import scheme
from pydantic import BaseModel, Field

scheme()
class SummarizeText(BaseModel):
    model: Optional[str] = Field(
        'none', description='Name of the model to use in the pipeline'
    )
