# generated by datamodel-codegen:
#   filename:  convert_pdf_to_markdown_model.json
#   timestamp: 2024-03-06T12:55:54+00:00

from __future__ import annotations
from malevich.square import scheme

from pydantic import BaseModel, Field


scheme()
class ConvertPdfToMarkdown(BaseModel):
    write_contents: bool = Field(
        ...,
        description='If true, contents of the file will be produced in the output rather than just the path to the file',
    )
