# generated by datamodel-codegen:
#   filename:  convert_pdf_to_markdown_model.json
#   timestamp: 2024-03-23T14:20:37+00:00

from __future__ import annotations

from typing import Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class ConvertPdfToMarkdown(BaseModel):
    start_page: Optional[int] = Field(0, description='From which page to start')
    page_num: Optional[int] = Field(0, description='Number of pages to retrieve')
