# generated by datamodel-codegen:
#   filename:  execute_model.json

from __future__ import annotations
from malevich.square import scheme

from pydantic import BaseModel, Field


@scheme()
class Execute(BaseModel):
    url: str = Field(..., description='URL of the DB to connect to')
    subsequent: bool = Field(
        ...,
        description='if True, each statement will be commited before the next one is executed',
    )
