# generated by datamodel-codegen:
#   filename:  http_request_model.json
#   timestamp: 2024-03-18T14:55:18+00:00

from __future__ import annotations
from malevich.square import scheme

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


scheme()
class HttpRequest(BaseModel):
    method: Optional[str] = Field('GET', description='Request method')
    headers: Optional[Dict[str, Any]] = Field({}, description='Request headers')
    body_type: Optional[str] = Field(
        'json',
        description="Body content type. One of the ['text', 'json', 'file', 'encoded']",
    )
    output_format: Optional[str] = Field(
        'text',
        description='Output format. For `text` returns the reponse in text format. For `file` will save result into a file and return filename',
    )
