# generated by datamodel-codegen:
#   filename:  execute_model.json

from __future__ import annotations
from malevich.square import scheme

from typing import List, Optional

from pydantic import BaseModel, Field


@scheme()
class Execute(BaseModel):
    args_map: List = Field(
        ...,
        description='List of collection aliases. Must be in order of input dataframes',
    )
    reverse_id: str = Field(..., description='Reverse ID of flow, you want to run')
    deployment_id: Optional[str] = Field(
        None, description='Deployment ID of flow, you want to run'
    )
    prepare: Optional[bool] = Field(
        False, description='Create new deployment and use it'
    )
    attach_to_last: Optional[bool] = Field(
        False, description='Use the last created active deployment'
    )
    timeout: Optional[int] = Field(150, description='Time to wait')
