select=["E", "F", "I", "W", "N", "UP", "ANN"]
ignore=["ANN101", "ANN001", "ANN002", "ANN003", "ANN101", "ANN201"]
exclude=["tests/*.py", "examples/*.py", "lib/src/*/apps/*/models/*.py"]

[per-file-ignores]
"__init__.py" = ["E402", "F", "I"]


