lint.select=["E", "F", "I", "W", "N", "UP", "ANN"]
lint.ignore=["ANN101", "ANN001", "ANN002", "ANN003", "ANN101", "ANN201", "RUF013", "ANN401"]
exclude=["tests/*.py", "examples/*.py", "*_model.py", "_train.py"]

[lint.per-file-ignores]
"__init__.py" = ["E402", "F", "I"]