# generated by datamodel-codegen:
#   filename:  filter_model.json
#   timestamp: 2024-03-06T17:15:23+00:00

from __future__ import annotations
from malevich.square import scheme

from typing import Any

from pydantic import BaseModel, Field


scheme()
class Filter(BaseModel):
    column: str = Field(..., description='The column to filter on')
    operation: str = Field(..., description='The operation to perform')
    value: Any = Field(..., description='The value to filter on')
    type: str = Field(..., description='The type of the value to filter on (optional)')
