# generated by datamodel-codegen:
#   filename:  filter_model.json
#   timestamp: 2024-03-05T16:28:33+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class Filter(BaseModel):
    column: str = Field(..., description='The column to filter on')
    operation: str = Field(..., description='The operation to perform')
    value: Any = Field(..., description='The value to filter on')
    type: str = Field(..., description='The type of the value to filter on (optional)')
