# generated by datamodel-codegen:
#   filename:  filter_model.json

from __future__ import annotations

from typing import Any, Dict, List, Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class Filter(BaseModel):
    conditions: Optional[List[Dict[str, Any]]] = Field(
        [], description='A list of conditions containing dictionaries'
    )
