# generated by datamodel-codegen:
#   filename:  subset_model.json

from __future__ import annotations

from typing import Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class Subset(BaseModel):
    expr: Optional[str] = Field(
        None,
        description='A comma-separated list of integers or slices, e.g. `0,1:3,5:7,6,9:10`. The first dataframe has index 0',
    )
