# generated by datamodel-codegen:
#   filename:  unwrap_model.json

from __future__ import annotations

from typing import List, Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class Unwrap(BaseModel):
    columns: Optional[List[str]] = Field(
        ['all'],
        description='The columns to unwrap. If not specified, all columns will be unwrapped',
    )
    delimiter: Optional[str] = Field(
        ',',
        description='The delimiter used to separate values in the columns. If not specified, the default delimiter is a comma (,)',
    )
