# generated by datamodel-codegen:
#   filename:  unwrap_model.json
#   timestamp: 2024-03-06T15:14:51+00:00

from __future__ import annotations
from malevich.square import scheme

from typing import List, Optional

from pydantic import BaseModel, Field


scheme()
class Unwrap(BaseModel):
    columns: Optional[List[str]] = Field(
        ['all'],
        description='The columns to unwrap. If not specified, all columns will be unwrapped',
    )
    delimiter: Optional[str] = Field(
        ',',
        description='The delimiter used to separate values in the columns. If not specified, the default delimiter is a comma (,)',
    )
