variables:
  MODE: "python"  # {python, pyspark}

# if build fail with oom - try add flag `--compressed-caching=false` to `/kaniko/executor` (script for app in ci)

before_script:
  - mkdir -p /kaniko/.docker
  - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_JOB_TOKEN}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
stages:
  - build_utility

build_utility:
  image: 
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: []
  stage: build_utility
  only:
    - master
    - main
    - dev
  tags:
   - julius_runner_apps
  script:
    - /kaniko/executor --context ./ --build-arg mode=${MODE} --build-arg branch=${CI_COMMIT_REF_NAME} --destination ${CI_REGISTRY_IMAGE}:latest --cleanup
