# generated by datamodel-codegen:
#   filename:  get_links_to_files_model.json
#   timestamp: 2024-03-06T12:29:19+00:00

from __future__ import annotations
from malevich.square import scheme

from typing import Optional

from pydantic import BaseModel, Field


scheme()
class GetLinksToFiles(BaseModel):
    expiration: Optional[int] = Field(
        21600,
        description='The number of seconds after which the link will expire. Defaults to 6 hours. Maximum is 24 hours',
    )
