# generated by datamodel-codegen:
#   filename:  get_links_to_files_model.json
#   timestamp: 2024-03-05T17:40:29+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class GetLinksToFiles(BaseModel):
    expiration: Optional[int] = Field(
        21600,
        description='The number of seconds after which the link will expire. Defaults to 6 hours. Maximum is 24 hours',
    )
