# generated by datamodel-codegen:
#   filename:  download_from_google_drive_model.json

from __future__ import annotations

from typing import Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class DownloadFromGoogleDrive(BaseModel):
    fail_on_error: Optional[bool] = Field(
        False, description='If True, the app will fail if any of the links are invalid'
    )
