# generated by datamodel-codegen:
#   filename:  download_from_google_drive_model.json
#   timestamp: 2024-03-06T12:29:20+00:00

from __future__ import annotations
from malevich.square import scheme

from typing import Optional

from pydantic import BaseModel, Field


scheme()
class DownloadFromGoogleDrive(BaseModel):
    fail_on_error: Optional[bool] = Field(
        False, description='If True, the app will fail if any of the links are invalid'
    )
