# generated by datamodel-codegen:
#   filename:  detect_raw_model.json

from __future__ import annotations

from typing import Any, Dict, Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class DetectRaw(BaseModel):
    weights: Optional[str] = Field(
        'yolo.pt', description='A path to the weights file in the shared storage'
    )
    conf: Optional[float] = Field(0.25, description='Confidence threshold')
    iou: Optional[float] = Field(0.45, description='IoU threshold')
    classes: Optional[Dict[str, Any]] = Field(
        {}, description='A dictionary that maps class ids to class names'
    )
    save_plots: Optional[bool] = Field(
        False, description='Whether to save the output images'
    )
    save_path: Optional[str] = Field(
        'default', description='The pattern for the path to the output images'
    )
    batch_size: Optional[int] = Field(1, description='The batch size')
