# generated by datamodel-codegen:
#   filename:  detect_raw_model.json
#   timestamp: 2024-03-05T17:40:29+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


class DetectRaw(BaseModel):
    weights: Optional[str] = Field(
        'yolo.pt', description='A path to the weights file in the shared storage'
    )
    conf: Optional[float] = Field(0.25, description='Confidence threshold')
    iou: Optional[float] = Field(0.45, description='IoU threshold')
    classes: Optional[Dict[str, Any]] = Field(
        {}, description='A dictionary that maps class ids to class names'
    )
    save_plots: Optional[bool] = Field(
        False, description='Whether to save the output images'
    )
    save_path: Any = Field(
        ..., description='The pattern for the path to the output images'
    )
    batch_size: Optional[int] = Field(1, description='The batch size')
