# generated by datamodel-codegen:
#   filename:  match_pattern_model.json
#   timestamp: 2024-03-13T13:09:13+00:00

from __future__ import annotations

from typing import Optional

from malevich.square import scheme
from pydantic import BaseModel, Field

scheme()
class MatchPattern(BaseModel):
    pattern: str = Field(..., description='A regular expression pattern to match')
    join_char: Optional[str] = Field(
        ';', description='A character to join the matches with'
    )
