# generated by datamodel-codegen:
#   filename:  add_column_model.json

from __future__ import annotations

from typing import Any, Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class AddColumn(BaseModel):
    column: Optional[str] = Field(
        'new_column', description='The name of the new column'
    )
    value: Optional[Any] = Field('new_value', description='The value of the new column')
    position: Optional[int] = Field(
        0,
        description='The position to insert the new column. If positive, the new column will be inserted from the beginning of the dataframe. If negative, the new column will be inserted from the end of the dataframe',
    )
    skip_if_exists: Optional[bool] = Field(
        False,
        description="If set, the processor will not raise exeception if column exists."
    )
