# generated by datamodel-codegen:
#   filename:  resize_model.json
#   timestamp: 2024-03-05T16:28:33+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Resize(BaseModel):
    width: Optional[int] = Field(None, description='The width of the resized image')
    height: Optional[int] = Field(None, description='The height of the resized image')
    preserve_ratio: Optional[bool] = Field(
        True, description='If True, the aspect ratio of the image will be preserved'
    )
    image_type: Optional[str] = Field(
        'jpg',
        description='The type of the image. Beware that some reformats may not support transparency',
    )
