# generated by datamodel-codegen:
#   filename:  download_model.json
#   timestamp: 2024-03-05T16:28:33+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Download(BaseModel):
    prefix: Optional[str] = Field(
        '',
        description='A prefix to add to the paths of downloaded files. If not specified, files will be downloaded to the root of the app directory',
    )
