# generated by datamodel-codegen:
#   filename:  change_json_model.json

from __future__ import annotations
from malevich.square import scheme

from typing import Optional

from pydantic import BaseModel, Field


@scheme()
class ChangeJson(BaseModel):
    path: str = Field(..., description='The path to follow in format "key1.key2.key3" ')
    raise_on_error: Optional[str] = Field(
        True, description='Raise error if nothing was found by the path'
    )
