from .scrape_aliexpress_model import ScrapeAliexpress
from .scrape_bing_search_model import ScrapeBingSearch
from .scrape_by_selectors_model import ScrapeBySelectors
from .scrape_google_search_model import ScrapeGoogleSearch
from .scrape_text_model import ScrapeText
from .scrape_web_model import ScrapeWeb
from .scrape_yamarket_api_model import ScrapeYamarketApi
