# generated by datamodel-codegen:
#   filename:  scrape_yamarket_api_model.json

from __future__ import annotations
from malevich.square import scheme

from typing import Optional

from pydantic import BaseModel, Field


@scheme()
class ScrapeYamarketApi(BaseModel):
    business_id: str = Field(..., description='Yandex Market business_id')
    api_token: str = Field(..., description='Yandex Market API token')
    max_image_links: Optional[int] = Field(
        None, description='Max amount of images per product'
    )
