# generated by datamodel-codegen:
#   filename:  scrape_wildberries_model.json

from __future__ import annotations
from malevich.square import scheme

from typing import Optional

from pydantic import BaseModel, Field


@scheme()
class ScrapeWildberries(BaseModel):
    max_results: Optional[int] = Field(
        3, description='The amount of images to retrieve'
    )
    output_type: Optional[str] = Field(
        'text', description="Format of text data. Either 'text' or 'json'"
    )
