# generated by datamodel-codegen:
#   filename:  scrape_yamarket_api_model.json
#   timestamp: 2024-03-23T14:20:37+00:00

from __future__ import annotations

from typing import Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class ScrapeYamarketApi(BaseModel):
    business_id: str = Field(..., description='Yandex Market business_id')
    api_token: str = Field(..., description='Yandex Market API token')
    max_image_links: Optional[int] = Field(
        None, description='Max amount of images per product'
    )
