# generated by datamodel-codegen:
#   filename:  rename_model.json
#   timestamp: 2024-03-05T17:40:29+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class Rename(BaseModel):
    old_column_name: Optional[str] = Field(
        "''",
        description="Provides mapping of old column names to their new names. For example 'a': 'A'",
    )
