# generated by datamodel-codegen:
#   filename:  send_message_model.json
#   timestamp: 2024-03-05T17:40:29+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class SendMessage(BaseModel):
    token: str = Field(..., description='Slack token')
