# generated by datamodel-codegen:
#   filename:  send_message_model.json

from __future__ import annotations

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class SendMessage(BaseModel):
    token: str = Field(..., description='Slack token')
