# generated by datamodel-codegen:
#   filename:  send_message_model.json
#   timestamp: 2024-03-13T12:50:20+00:00

from __future__ import annotations

from malevich.square import scheme
from pydantic import BaseModel, Field

scheme()
class SendMessage(BaseModel):
    token: str = Field(..., description='Slack token')
