# generated by datamodel-codegen:
#   filename:  speech_to_text_model.json

from __future__ import annotations

from typing import Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class SpeechToText(BaseModel):
    openai_api_key: str = Field(..., description='Your OpenAI API key')
    language: Optional[str] = Field(
        'en', description='The language to transcribe audio to'
    )
    temperature: Optional[float] = Field(0.9, description='The temperature')
    prompt: Optional[str] = Field(
        None, description='A short optional prompt to guide the model'
    )
