# generated by datamodel-codegen:
#   filename:  text_to_speech_model.json
#   timestamp: 2024-03-23T14:20:37+00:00

from __future__ import annotations

from typing import Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class TextToSpeech(BaseModel):
    openai_api_key: str = Field(..., description='Your OpenAI API key')
    model: Optional[str] = Field('tts-1', description='The model to use')
    voice: Optional[str] = Field(
        'alloy',
        description="The voice to use. One of 'alloy', 'echo', 'fable', 'onyx', 'nova', and 'shimmer'",
    )
