# generated by datamodel-codegen:
#   filename:  text_to_image_model.json

from __future__ import annotations

from typing import Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class TextToImage(BaseModel):
    openai_api_key: str = Field(..., description='Your OpenAI API key')
    user_prompt: str = Field(..., description='The prompt for the user')
    model: Optional[str] = Field('dall-e-3', description='The model to use')
    download: Optional[bool] = Field(False, description='Whether to download images')
    n: Optional[int] = Field(
        1, description='Amount of images to generate for each request'
    )
