FROM pogrebnoijak/julius_export_python:0.1

COPY ./lib/src/drives/requirements.txt ./requirements.txt   
RUN if test -e requirements.txt; then pip install --no-cache-dir -r requirements.txt; fi

COPY ./lib/src/drives/apps ./apps
COPY ./mosaic ./mosaic