# generated by datamodel-codegen:
#   filename:  get_page_crawlbase_ali_model.json

from __future__ import annotations
from malevich.square import scheme

from typing import Optional

from pydantic import BaseModel, Field


@scheme()
class GetPageCrawlbaseAli(BaseModel):
    token: str = Field(..., description='API token (CrawlBase or ScrapeAPI)')
    api: Optional[str] = Field(
        'crawlbase', description='Which API to use: CrawlBase or ScrapeAPI'
    )
