# generated by datamodel-codegen:
#   filename:  get_page_crawlbase_ali_model.json

from __future__ import annotations
from malevich.square import scheme

from pydantic import BaseModel, Field


@scheme()
class GetPageCrawlbaseAli(BaseModel):
    token: str = Field(..., description='CrawlBase API token (https://crawlbase.com/)')
