# generated by datamodel-codegen:
#   filename:  get_page_with_proxy_model.json

from __future__ import annotations
from malevich.square import scheme

from typing import Any, Dict, Optional

from pydantic import BaseModel, Field


@scheme()
class GetPageWithProxy(BaseModel):
    token: str = Field(..., description='API token (CrawlBase or ScrapeAPI)')
    api: Optional[str] = Field(
        'crawlbase', description='Which API to use: CrawlBase or ScrapeAPI'
    )
    proxy_config: Optional[Dict[str, Any]] = Field(
        {},
        description='Config with request parameters. Reffer to [Crawlbase Docs](https://crawlbase.com/docs/crawling-api/parameters) or [Scrape Docs](https://docs.scraperapi.com/making-requests/customizing-requests)',
    )
