# generated by datamodel-codegen:
#   filename:  get_page_model.json

from __future__ import annotations
from malevich.square import scheme

from typing import Optional

from pydantic import BaseModel, Field


@scheme()
class GetPage(BaseModel):
    follow_redirects: Optional[bool] = Field(
        False, description='Follow redirect if 3xx code is received'
    )
