# generated by datamodel-codegen:
#   filename:  assert_regex_model.json
#   timestamp: 2024-03-06T12:29:20+00:00

from __future__ import annotations
from malevich.square import scheme

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


scheme()
class AssertRegex(BaseModel):
    rules: List[Dict[str, Any]] = Field(..., description='The rules to apply')
    raise_on_error: Optional[bool] = Field(
        False, description='Whether to raise an exception if an error is found'
    )
