# generated by datamodel-codegen:
#   filename:  assert_regex_model.json

from __future__ import annotations

from typing import Any, Dict, List, Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class AssertRegex(BaseModel):
    rules: Optional[List[Dict[str, Any]]] = Field([], description='The rules to apply')
    raise_on_error: Optional[bool] = Field(
        False, description='Whether to raise an exception if an error is found'
    )
