# generated by datamodel-codegen:
#   filename:  assert_links_model.json
#   timestamp: 2024-03-23T14:20:37+00:00

from __future__ import annotations

from typing import Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class AssertLinks(BaseModel):
    filter_links: Optional[bool] = Field(
        False,
        description='If set to True, will filter the dataframe and exclude invalid links',
    )
