# generated by datamodel-codegen:
#   filename:  split_on_frames_model.json
#   timestamp: 2024-03-06T12:29:19+00:00

from __future__ import annotations
from malevich.square import scheme

from typing import Optional, Union

from pydantic import BaseModel, Field


scheme()
class SplitOnFrames(BaseModel):
    fps: Optional[Union[int, float]] = Field(
        1,
        description='Frames per second. If float is used then it is used as a percentage of the original fps',
    )
