# generated by datamodel-codegen:
#   filename:  upload_images_to_task_model.json

from __future__ import annotations

from typing import Optional

from malevich.square import scheme
from pydantic import BaseModel, Field


@scheme()
class UploadImagesToTask(BaseModel):
    cvat_url: str = Field(..., description='URL of your CVAT server')
    cvat_user: str = Field(..., description='Account user name on CVAT')
    cvat_password: str = Field(..., description='Account user password on CVAT')
    cvat_org: Optional[str] = Field(
        '', description='CVAT organization. By default uses personal workspace'
    )
    project_id: str = Field(..., description='ID of CVAT project')
    cloud_id: str = Field(..., description='ID of cloud storage')
    aws_access_key_id: str = Field(..., description='AWS credentials')
    aws_secret_access_key: str = Field(..., description='AWS credentials')
    endpoint_url: Optional[str] = Field(
        'AWS S3 endpoint', description='URL endpoint of the cloud storage (S3)'
    )
    bucket_name: Optional[str] = Field('cvat', description='Name of S3 bucket')
