name: ECR build push
on:  
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_push:
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'branch' }} && ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with: 
          fetch-depth: 0
      - name: Malevich Actions
        uses: MalevichAI/auto-ci@v0.1.0
        with:
          registry: "ecr"
          registry_url: "public.ecr.aws"
          registry_id: "u6e1k0c7"
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
