name: ECR build push
on: [push, workflow_dispatch]
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
      - name: Docker login
        run: |
          AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} AWS_SECRET_ACCESS_KEY={{$AWS_SECRET_ACCESS_KEY}} aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{secrets.AWS_ECR}}
      - name: Docker logout
        run: docker logout
