name: ECR build push
on: 
  push:
    branches: 
      - ramprin-ecr
  workflow_dispatch:
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with: 
          fetch-depth: 0
      - name: Malevich Actions
        uses: RamPrin/push_folders@v0.1.0
        with:
          registry: "ecr"
          registry_url: "public.ecr.aws"
          registry_id: "u6e1k0c7/malevich"
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
