name: Malevich Manual CI at main
on:  
  workflow_dispatch:
jobs:
  build_push:
    environment: main
    runs-on: ubuntu-latest
    if: ${{ github.ref_type == 'branch' }} && ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Malevich CI Actions
        uses: MalevichAI/auto-ci@v0.2.0
        with:
          registry: ${{ secrets.REGISTRY_TYPE }}
          registry_url: ${{ secrets.REGISTRY_URL }}
          registry_id: ${{ secrets.REGISTRY_ID }}
          username: ${{ secrets.IMAGE_USERNAME }}
          password: ${{ secrets.IMAGE_PASSWORD }}
          space_username: ${{ secrets.SPACE_USERNAME }}
          space_password: ${{ secrets.SPACE_PASSWORD }}
          api_url: ${{ secrets.API_URL }}
          org_id: ${{ secrets.SPACE_ORGANIZATION_ID }}